# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Demo
  pod 'Axe' , :path => '../../Axe.podspec' , :subspecs => [
    'Core',
    'TabBarController',
    'Html',
    'React'
    ]
  pod 'MXReact', :podspec => '/Users/luoxianming/git/react-native/MXReact.podspec' , :subspecs =>  [
   'Core',
   'CxxBridge', # Include this for RN >= 0.47
   'RCTText',
   'RCTNetwork',
   'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
   'RCTWebSocket', 
  ]

end
